### ISSUE TITLE
About android api testing

### ISSUE THREAD

**Issue by lynnyoo** [aosp-mirror/platform_frameworks_base#137]
Hi,guys.
I have a question there，
HOW TO DO API TESTING WITH Android?
I tried some api testing tools，such as soapui,postman,etc.
But them just couldn't work:(

**Comment by Niranjan-B** [comment]
What exactly do you mean by API testing on Android? Do you mean API's provided by the Android framework? Because in that context, postman doesn't even come into picture. Postman is mostly used for testing API's offered by a server. 
There are a lot of testing frameworks. 
I personally use Espresso for instrumentation tests -> https://google.github.io/android-testing-support-library/docs/espresso/ and Roboelectric for unit tests -> http://robolectric.org/

**Comment by lynnyoo** [comment]
Thanks for your detailed answer.
Exactly, I wonder there ought to be another solution to this.
Could I use some tools,just testing API's function(not unit test)?

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
